-- 添加知识库ID字段到T_AI_CONVERSATIONS表
-- 此脚本用于支持对话记录关联的知识库功能

USE ai_test;

-- 检查字段是否已存在
IF NOT EXISTS (
    SELECT * FROM sys.columns 
    WHERE object_id = OBJECT_ID('T_AI_CONVERSATIONS') 
    AND name = 'KNOWLEDGE_BASE_ID'
)
BEGIN
    -- 添加KNOWLEDGE_BASE_ID字段
    ALTER TABLE T_AI_CONVERSATIONS 
    ADD KNOWLEDGE_BASE_ID NVARCHAR(50) NULL;
    
    PRINT '成功添加KNOWLEDGE_BASE_ID字段到T_AI_CONVERSATIONS表';
END
ELSE
BEGIN
    PRINT 'KNOWLEDGE_BASE_ID字段已存在，跳过添加';
END

-- 创建索引以提高查询性能（可选）
IF NOT EXISTS (
    SELECT * FROM sys.indexes 
    WHERE object_id = OBJECT_ID('T_AI_CONVERSATIONS') 
    AND name = 'IX_T_AI_CONVERSATIONS_KNOWLEDGE_BASE_ID'
)
BEGIN
    CREATE NONCLUSTERED INDEX IX_T_AI_CONVERSATIONS_KNOWLEDGE_BASE_ID
    ON T_AI_CONVERSATIONS (KNOWLEDGE_BASE_ID);
    
    PRINT '成功创建KNOWLEDGE_BASE_ID索引';
END
ELSE
BEGIN
    PRINT 'KNOWLEDGE_BASE_ID索引已存在，跳过创建';
END